### ISSUE TITLE
Go through the security checklist for public repos

### ISSUE THREAD

**Issue by fmarier** [brave/playlist-component#3]
https://github.com/brave/internal/wiki/Pull-request-security-audit-checklist#github-repository-security (just the *Github repository security* section)

**Comment by sangwoo108** [comment]
- [ ] Do all outside collaborators have only the minimum necessary access? Have old collaborators been removed?
- [ ] Has 'branch protection' been set up on the master and release branches? See https://github.com/brave/internal/issues/150 for recommended settings.
- [ ] If this repository added 3rd party github apps/integrations, have they been audited and/or removed if no longer needed?
- [ ] Do the github issues for this repo have a security label set up for security issue reporting?
- [ ] Wiki is disabled unless needed. Restrict wiki permissions to collaborators only (See: https://help.github.com/articles/changing-access-permissions-for-wikis/)
- [ ] Set up Github security alerts (Dependabot) in the repo settings and make sure the repo maintainers are getting these alerts. https://github.blog/2017-11-16-introducing-security-alerts-on-github/
- [ ] Set up Github automatic security fixes (Dependabot): https://help.github.com/en/articles/configuring-automated-security-fixes
- [ ] Set up automated CodeQL security scanning in https://github.com/brave/$YOUR_REPO_NAME/security/code-scanning if available
- [ ] Does this project have a LICENSE file? (not needed for private repos)
- [ ] Has security.md file (see https://github.com/brave/brave-browser/blob/master/SECURITY.md for example)
- [ ] If intended to be used in prod, there should be no dependencies in the brave-experiments org or on employee's personal repos
- [ ] Inform the security team of the newly created repository, Cc @sec-team in the #secops channel. This step is required to allow for the security team to supervision new security issues affecting the repository.
- [ ] use pull_request, not pull_request_target for github actions
